### ISSUE TITLE
require 'EGP_Rates' isn't working 

### ISSUE THREAD

**Issue by muhammednagy** [mad-raz/EGP-Rates#23]
hello 
I tried to use the gem in my rails project. I added it to Gemfile and I hit bundle i .
every time I use require 'EGP_Rates' it shows me this error:
LoadError: cannot load such file -- EGP_Rates

The solution is to use require 'egp_rates'
or change the name of egp_rates.rb in lib to be EGP_Rates.rb

**Comment by mad-raz** [comment]
thanks 👍

**Comment by muhammednagy** [comment]
i know i was trying it in a script first

**Comment by mad-raz** [comment]
yeah, thanks for noticing this in the documentation
I forgot to update it when I built the CLI
https://github.com/mad-raz/EGP-Rates-CLI/blob/master/lib/EGP_Rates_CLI.rb#L2

**Comment by muhammednagy** [comment]
:)
thanks for your code and your tiime
