### ISSUE TITLE
Remove `FaisalBank` support

### ISSUE THREAD

**Issue by mad-raz** [mad-raz/EGP-Rates#29]
`EGPRates::FaisalBank` has been failing the live testing long time ago (and stopped providing the data on their "sub-optimal urban" website)
It should be fixed or preferably removed. 

reference to the failing builds https://app.wercker.com/artmees/EGP-Rates/runs

**Comment by muhammednagy** [comment]
Okay i'm working on it !

**Comment by muhammednagy** [comment]
It seems like they completely deleted the exchange rates page I'll be deleting FaisalBank

**Comment by mad-raz** [comment]
👍

**Comment by muhammednagy** [comment]
done
